contact_links:
  - name: Ask a question for self-hosting
    url: https://github.com/codingsoftmx/lobehub/discussions/new?category=self-hosting
    about: Please post questions, and ideas in discussions.
  - name: Questions and ideas
    url: https://github.com/codingsoftmx/lobehub/discussions/new/choose
    about: Please post questions, and ideas in discussions.
